import * as THREE from 'three';
import {
  OUTCOME_COLORS, OUTCOME_LABELS,
  SIZE_TAGS, SIZE_LABELS, PARTICLE_SUMMARY,
  TRACKING_PARAMS,
  buildSeedPositions, buildSchematicTerminals, buildSchematicPaths,
} from '../../data/particleData.js';

/**
 * Particle visualization — Two modes:
 *   SCHEMATIC : uses deterministic geometry-derived terminal positions
 *               (Phase 12B did not store trajectory path coordinates)
 *   REAL      : loaded from threejs/public/data/particleTrajectories.json
 *               (generated by running tools/export_particle_trajectories.py)
 *
 * All geometry uses BufferGeometry + line-batching for performance.
 * Coordinate system: Three.js (THREE_x = CAD_x−0.350, THREE_y = CAD_z−0.925, THREE_z = CAD_y−0.400)
 */

const CAD_TO_THREE = ([x, y, z]) => [x, y, z]; // already pre-converted in particleData.js

let _group = null;
let _realLoaded = false;

// Per-size, per-outcome mesh handles { tag → { outcome → mesh } }
const _lineMeshes  = {};
const _seedMeshes  = {};
const _termMeshes  = {};

// Active visibility state
let _visibleSize    = null;  // null = all
let _visibleOutcomes = new Set(['FILTER_ARRIVAL', 'FRAME_DEPOSIT', 'WALL_DEPOSIT', 'RECIRCULATION']);

// ── Public API ───────────────────────────────────────────────────────────────

export async function createParticles(scene) {
  _group = new THREE.Group();
  _group.name = 'ParticleGroup';
  _group.visible = false;

  // Try loading real trajectories first
  let realData = null;
  try {
    const resp = await fetch('./data/particleTrajectories.json');
    if (resp.ok) {
      realData = await resp.json();
      _realLoaded = true;
      console.log('[Particles] Real trajectory data loaded:', realData.n_trajectories, 'trajectories');
    }
  } catch {
    // No real data — schematic mode
  }

  if (realData) {
    _buildRealGeometry(realData);
  } else {
    _buildSchematicGeometry();
  }

  scene.add(_group);
  return _group;
}

export function isRealDataLoaded() { return _realLoaded; }

export function setParticleGroupVisible(v) {
  if (_group) _group.visible = v;
}

export function filterBySize(tag) {
  // tag = '0p3um' | '1um' | '2p5um' | '10um' | null (all)
  _visibleSize = tag;
  _applyFilters();
}

export function filterByOutcome(outcomes) {
  // outcomes: array of outcome keys
  _visibleOutcomes = new Set(outcomes);
  _applyFilters();
}

// ── Schematic geometry ───────────────────────────────────────────────────────

function _buildSchematicGeometry() {
  const seedPositions = buildSeedPositions();

  for (const tag of SIZE_TAGS) {
    _lineMeshes[tag]  = {};
    _seedMeshes[tag]  = {};
    _termMeshes[tag]  = {};

    const terminals = buildSchematicTerminals(tag);
    const paths     = buildSchematicPaths(seedPositions, terminals, tag);

    // Seed cloud (all sizes share the same seed grid)
    _seedMeshes[tag].seeds = _makePoints(
      seedPositions.map(p => p),
      0x4488cc, 0.4, 2.5
    );
    _group.add(_seedMeshes[tag].seeds);

    // Per-outcome: lines + terminal points
    for (const outcome of ['FILTER_ARRIVAL', 'FRAME_DEPOSIT', 'WALL_DEPOSIT']) {
      const col  = OUTCOME_COLORS[outcome];
      const pts  = paths[outcome];   // [[seed, term], ...] flat
      const terms = terminals.filter(t => t.outcome === outcome).map(t => t.pos);

      // Line segments (seed → terminal, schematic)
      if (pts.length > 0) {
        _lineMeshes[tag][outcome] = _makeLineSegments(pts, col, 0.25);
        _group.add(_lineMeshes[tag][outcome]);
      }

      // Terminal dots
      if (terms.length > 0) {
        _termMeshes[tag][outcome] = _makePoints(terms, col, 0.75, 4.0);
        _group.add(_termMeshes[tag][outcome]);
      }
    }
  }
}

// ── Real trajectory geometry ─────────────────────────────────────────────────

function _buildRealGeometry(data) {
  // THREE.js conversion from CAD coords
  const c = ([x, y, z]) => [x - 0.350, z - 0.925, y - 0.400];

  for (const tag of SIZE_TAGS) {
    _lineMeshes[tag]  = {};
    _seedMeshes[tag]  = {};
    _termMeshes[tag]  = {};

    const byOutcome = { FILTER_ARRIVAL: [], FRAME_DEPOSIT: [], WALL_DEPOSIT: [], RECIRCULATION: [] };

    for (const traj of data.trajectories) {
      if (traj.tag !== tag) continue;
      const pts = traj.points.map(c);
      const out = traj.final_status;
      if (!byOutcome[out]) byOutcome[out] = [];
      byOutcome[out].push({ pts, seed: c(traj.seed) });
    }

    // Seeds
    const allSeeds = [...byOutcome.FILTER_ARRIVAL, ...byOutcome.FRAME_DEPOSIT,
                      ...byOutcome.WALL_DEPOSIT,   ...byOutcome.RECIRCULATION]
                     .map(t => t.seed);
    if (allSeeds.length > 0) {
      _seedMeshes[tag].seeds = _makePoints(allSeeds, 0x4488cc, 0.5, 2.5);
      _group.add(_seedMeshes[tag].seeds);
    }

    for (const [outcome, trajs] of Object.entries(byOutcome)) {
      if (!trajs.length) continue;
      const col = OUTCOME_COLORS[outcome];

      // Build polyline segments: consecutive pairs from each trajectory
      const lineVerts = [];
      const termPts   = [];
      for (const { pts } of trajs) {
        for (let i = 0; i < pts.length - 1; i++) {
          lineVerts.push(pts[i], pts[i + 1]);
        }
        termPts.push(pts[pts.length - 1]);
      }

      if (lineVerts.length > 0) {
        _lineMeshes[tag][outcome] = _makeLineSegments(lineVerts, col, 0.40);
        _group.add(_lineMeshes[tag][outcome]);
      }
      if (termPts.length > 0) {
        _termMeshes[tag][outcome] = _makePoints(termPts, col, 0.80, 5.0);
        _group.add(_termMeshes[tag][outcome]);
      }
    }
  }
}

// ── Filters ──────────────────────────────────────────────────────────────────

function _applyFilters() {
  for (const tag of SIZE_TAGS) {
    const sizeVis = (_visibleSize === null || _visibleSize === tag);

    if (_seedMeshes[tag]?.seeds) {
      _seedMeshes[tag].seeds.visible = sizeVis;
    }

    for (const outcome of Object.keys(OUTCOME_COLORS)) {
      const outcomeVis = _visibleOutcomes.has(outcome);
      const vis = sizeVis && outcomeVis;

      if (_lineMeshes[tag]?.[outcome]) _lineMeshes[tag][outcome].visible = vis;
      if (_termMeshes[tag]?.[outcome]) _termMeshes[tag][outcome].visible = vis;
    }
  }
}

// ── Geometry helpers ─────────────────────────────────────────────────────────

function _makePoints(positions, color, opacity, size) {
  const verts = new Float32Array(positions.length * 3);
  for (let i = 0; i < positions.length; i++) {
    verts[i * 3]     = positions[i][0];
    verts[i * 3 + 1] = positions[i][1];
    verts[i * 3 + 2] = positions[i][2];
  }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(verts, 3));

  const mat = new THREE.PointsMaterial({
    color, size: size ?? 3.0,
    opacity, transparent: opacity < 1,
    sizeAttenuation: false,
  });
  return new THREE.Points(geo, mat);
}

function _makeLineSegments(pairs, color, opacity) {
  // pairs: array of [x,y,z] points; consecutive pairs form segments
  const verts = new Float32Array(pairs.length * 3);
  for (let i = 0; i < pairs.length; i++) {
    verts[i * 3]     = pairs[i][0];
    verts[i * 3 + 1] = pairs[i][1];
    verts[i * 3 + 2] = pairs[i][2];
  }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(verts, 3));
  const mat = new THREE.LineBasicMaterial({ color, opacity, transparent: opacity < 1 });
  return new THREE.LineSegments(geo, mat);
}
